In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
orders = pd.read_csv(
    "./data/orders.csv",
    parse_dates=["order_date"]
)

order_items = pd.read_csv(
    "./data/order_items.csv"
)

products = pd.read_csv(
    "./data/products.csv"
)

customers = pd.read_csv(
    "./data/customers.csv",
    parse_dates=["signup_date"]
)

In [42]:
print(orders["order_date"].dtype)

datetime64[us]

In [43]:
orders["year"] = orders["order_date"].dt.year
orders["month"] = orders["order_date"].dt.month
orders["month_name"] = orders["order_date"].dt.month_name()
print(orders["year"].dtype, orders["month"].dtype, orders["month_name"].dtype)

int32 int32 str

In [44]:
orders.head()

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee,year,month,month_name
0,100001,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95,2024,1,January
1,100002,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00,2024,1,January
2,100003,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00,2024,1,January
3,100004,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00,2024,1,January
4,100005,3452,2024-01-01 17:44:03,completed,gift_card,NaN,0.00,2024,1,January

In [45]:
datasets = {
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "customers": customers
}

for name, df in datasets.items():
    print("=" * 50)
    print(name)
    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())
    print("\nData types:")
    print(df.dtypes)

==================================================
orders
Shape: (9245, 10)

Columns:
['order_id', 'customer_id', 'order_date', 'status', 'payment_method', 'discount_code', 'shipping_fee', 'year', 'month', 'month_name']

Data types:
order_id                   int64
customer_id                int64
order_date        datetime64[us]
status                       str
payment_method               str
discount_code                str
shipping_fee             float64
year                       int32
month                      int32
month_name                   str
dtype: object
==================================================
order_items
Shape: (15608, 5)

Columns:
['order_id', 'product_id', 'quantity', 'unit_price', 'discount_amount']

Data types:
order_id             int64
product_id           int64
quantity             int64
unit_price         float64
discount_amount    float64
dtype: object
==================================================
products
Shape: (90, 5)

Columns:
['product_id', 'product_name', 'category', 'list_price', 'unit_cost']

Data types:
product_id        int64
product_name        str
category            str
list_price      float64
unit_cost       float64
dtype: object
==================================================
customers
Shape: (3600, 4)

Columns:
['customer_id', 'signup_date', 'state', 'acquisition_channel']

Data types:
customer_id                     int64
signup_date            datetime64[us]
state                             str
acquisition_channel               str
dtype: object

In [46]:
for name, df in datasets.items():
    print("\n", name)
    print(df.isnull().sum())

 orders
order_id             0
customer_id          0
order_date           0
status               0
payment_method       0
discount_code     7834
shipping_fee         0
year                 0
month                0
month_name           0
dtype: int64

 order_items
order_id             0
product_id           0
quantity             0
unit_price         199
discount_amount      0
dtype: int64

 products
product_id      0
product_name    0
category        0
list_price      0
unit_cost       0
dtype: int64

 customers
customer_id            0
signup_date            0
state                  0
acquisition_channel    0
dtype: int64

In [47]:
orders["discount_code"] = orders["discount_code"].fillna("NO_DISCOUNT")

In [48]:
for name, df in datasets.items():
    print("\n", name)
    print(df.isnull().sum())

 orders
order_id          0
customer_id       0
order_date        0
status            0
payment_method    0
discount_code     0
shipping_fee      0
year              0
month             0
month_name        0
dtype: int64

 order_items
order_id             0
product_id           0
quantity             0
unit_price         199
discount_amount      0
dtype: int64

 products
product_id      0
product_name    0
category        0
list_price      0
unit_cost       0
dtype: int64

 customers
customer_id            0
signup_date            0
state                  0
acquisition_channel    0
dtype: int64

In [53]:
for name, df in datasets.items():
    print(name, "duplicates:", df.duplicated().sum())

orders duplicates: 38
order_items duplicates: 0
products duplicates: 0
customers duplicates: 0

In [50]:
duplicate_orders = orders[
    orders["order_id"].duplicated(keep=False)
].sort_values("order_id")

duplicate_orders

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee,year,month,month_name
47,100048,3320,2024-01-06 16:37:36,completed,credit_card,NO_DISCOUNT,6.95,2024,1,January
8560,100048,3320,2024-01-06 16:37:36,completed,credit_card,NO_DISCOUNT,6.95,2024,1,January
7556,100303,853,2024-02-03 08:33:22,completed,apple_pay,NO_DISCOUNT,0.00,2024,2,February
303,100303,853,2024-02-03 08:33:22,completed,apple_pay,NO_DISCOUNT,0.00,2024,2,February
5488,100710,526,2024-03-13 13:39:17,completed,credit_card,NO_DISCOUNT,0.00,2024,3,March
...,...,...,...,...,...,...,...,...,...,...
8617,108585,1995,2025-11-28 12:43:37,completed,apple_pay,HOLIDAY20,0.00,2025,11,November
9104,109068,1981,2025-12-20 13:27:25,completed,credit_card,HOLIDAY20,6.95,2025,12,December
3104,109068,1981,2025-12-20 13:27:25,completed,credit_card,HOLIDAY20,6.95,2025,12,December
4213,109087,3358,2025-12-22 08:35:44,completed,credit_card,HOLIDAY20,0.00,2025,12,December
9124,109087,3358,2025-12-22 08:35:44,completed,credit_card,HOLIDAY20,0.00,2025,12,December

In [51]:
orders = orders.drop_duplicates(subset="order_id")

In [54]:
duplicate_orders = orders[
    orders["order_id"].duplicated(keep=False)
].sort_values("order_id")

duplicate_orders

Empty DataFrame
Columns: [order_id, customer_id, order_date, status, payment_method, discount_code, shipping_fee, year, month, month_name]
Index: []

In [56]:
products["category"].value_counts()

category
Kitchen       10
Bath           9
Furniture      9
Outdoor        9
Bedding        8
Lighting       8
Decor          8
Storage        7
decor          4
 Kitchen       2
 Bedding       2
Storage        2
Kitchen        1
kitchen        1
KITCHEN        1
bedding        1
BEDDING        1
bath           1
Furniture      1
furniture      1
FURNITURE      1
LIGHTING       1
OUTDOOR        1
 Outdoor       1
Name: count, dtype: int64

In [59]:
products["category"] = (
    products["category"]
    .str.strip()
    .str.title()
)
products["category"].value_counts()

category
Kitchen      15
Bedding      12
Furniture    12
Decor        12
Outdoor      11
Bath         10
Lighting      9
Storage       9
Name: count, dtype: int64

In [60]:
order_items["unit_price"].isna().sum()

np.int64(199)